"""Learning a configuration from a file you already trust.

Every threshold Sift ships with is a guess about data it has never seen. A 10%
null rate is alarming in a payments export and unremarkable in a survey. A
constant column is a bug in one pipeline and the design in another.

`sift init` removes the guessing. Point it at a file that is known good, and
it writes the config that would make Sift quiet about *that* file — and only
that file. Everything it decided to accept is written down, in a file you
commit and review, with the reason attached. From then on, "clean" means
"looks like the file we agreed was fine", which is a far more useful standard
than any default this tool could ship.

The output is deliberately a config rather than a stored baseline copy. A
config is text: it goes in a pull request, someone reads the diff, and a line
that says `missing-values = ["email"]` invites the question "since when?" A
binary baseline sitting in a folder invites nothing.
"""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import date

from .config import Config
from .findings import Finding, Severity
from .loading import Table
from .profiling import CATEGORICAL, EMPTY
from .text import plural, terminal_safe

# Findings that describe a file's shape rather than its damage. These are the
# ones worth accepting from a good file — a zip code column really is all
# digits with leading zeros, and it will be tomorrow too.
SHAPE_CODES = {
    "leading-zeros",
    "constant-column",
    "high-cardinality",
    "missing-values",
    "disguised-null",
    "candidate-key",
    "compact-date-or-number",
    "european-numbers",
    "unexpected-negative",
    "outliers",
    "no-trailing-newline",
    "unread-sheets",
    "number-as-text",
}

# Findings that mean the file is damaged. Accepting these from a "known-good"
# baseline would bake a real defect into the definition of normal.
NEVER_ACCEPT = {
    "ragged-rows",
    "mojibake",
    "encoding",
    "mixed-types",
    "conflicting-date-formats",
    "conflicting-number-formats",
    "ambiguous-dates",
    "ambiguous-decimal-separator",
    "duplicate-column-name",
    "formula-error",
    "orphaned-reference",
}


def _quote(value: str) -> str:
    # JSON's string escapes are also valid TOML basic-string escapes.  Using
    # them here keeps control characters (including ESC and embedded newlines)
    # out of generated config text while preserving the exact column name when
    # tomllib reads the file back.
    return json.dumps(value, ensure_ascii=False)


def _wrap(text: str, width: int = 74) -> list[str]:
    words, line, out = text.split(), "", []
    for word in words:
        if len(line) + len(word) + 1 > width:
            out.append(line)
            line = word
        else:
            line = f"{line} {word}".strip()
    if line:
        out.append(line)
    return out


def build(table: Table, findings: list[Finding], key: list[str] | None = None) -> str:
    """Render the config that would make Sift quiet about this file."""
    accepted: dict[str, list[tuple[str, str]]] = defaultdict(list)
    global_ignores: list[tuple[str, str]] = []
    refused: list[Finding] = []

    for finding in findings:
        if finding.code in NEVER_ACCEPT:
            refused.append(finding)
            continue
        if finding.code == "candidate-key":
            continue  # becomes the `key` setting, not an exemption
        if finding.code not in SHAPE_CODES:
            refused.append(finding)
            continue
        if finding.column:
            accepted[finding.code].append((finding.column, finding.message))
        else:
            global_ignores.append((finding.code, finding.message))

    if key is None:
        key = [f.column for f in findings if f.code == "candidate-key" and f.column]

    lines = [
        "# Generated by `sift init` from " + terminal_safe(table.path.name),
        f"# on {date.today().isoformat()}, from {table.n_rows:,} rows "
        f"and {len(table.columns)} columns.",
        "#",
    ]
    lines += [
        "# " + line
        for line in _wrap(
            "Everything below was true of that file. Read it as a description of "
            "what normal looks like here, and change it when normal changes — a "
            "line you no longer agree with is the point of keeping this in "
            "version control."
        )
    ]
    lines += ["", "[sift]"]

    if key:
        lines.append(
            "# Unique and complete in the baseline, so it should stay that way."
        )
        lines.append("key = [" + ", ".join(_quote(name) for name in key) + "]")

    empties = [c.name for c in table.columns if c.profile.kind == EMPTY]
    worst_null = max((c.profile.null_rate for c in table.columns), default=0.0)
    lines.append("")
    lines.append(
        f"# The emptiest column in the baseline was {worst_null:.0%} null. "
        "Thresholds are"
    )
    lines.append(
        "# left at the defaults; specific columns that are legitimately sparse are"
    )
    lines.append("# exempted below rather than by loosening the rule for everything.")
    lines.append("null_warn = 0.10")
    lines.append("null_error = 0.50")
    lines.append('fail_on = "error"')

    if global_ignores:
        lines += ["", "# Accepted for the whole file:"]
        for _, message in global_ignores:
            lines += ["# " + line for line in _wrap(message)]
        lines.append(
            "ignore = [" + ", ".join(_quote(code) for code, _ in global_ignores) + "]"
        )

    if accepted:
        lines += [
            "",
            "# Accepted per column. Each of these fired on the baseline and was",
            "# judged to be how the data is, not what is wrong with it.",
            "[sift.ignore_columns]",
        ]
        for code in sorted(accepted):
            entries = accepted[code]
            lines.append("")
            for _, message in entries[:1]:
                lines += ["# " + line for line in _wrap(message)]
            if len(entries) > 1:
                lines.append(f"# ...and {plural(len(entries) - 1, 'other column')}.")
            columns = sorted({column for column, _ in entries})
            lines.append(
                f"{code} = [" + ", ".join(_quote(column) for column in columns) + "]"
            )

    if empties:
        note = (
            "Note: "
            + ", ".join(repr(name) for name in empties)
            + " had no values at all in the baseline, so nothing could be "
            "learned about them."
        )
        lines.append("")
        lines.extend("# " + line for line in _wrap(note))

    return "\n".join(lines) + "\n"


def describe(findings: list[Finding]) -> tuple[list[Finding], list[Finding]]:
    """Split findings into what a baseline may accept and what it may not."""
    refusable = [
        f
        for f in findings
        if f.code in NEVER_ACCEPT or (f.severity is Severity.ERROR and f.code not in SHAPE_CODES)
    ]
    acceptable = [f for f in findings if f not in refusable]
    return acceptable, refusable


def summarise(table: Table, findings: list[Finding], config: Config) -> str:
    """What init learned, in prose, for the person running it."""
    acceptable, refusable = describe(findings)
    categorical = [
        c.name for c in table.columns if c.profile.kind == CATEGORICAL
    ]
    lines = [
        f"Read {terminal_safe(table.path)} — {table.n_rows:,} rows, "
        f"{len(table.columns)} columns.",
        "",
        f"  {plural(len(acceptable), 'finding')} accepted as normal for this file.",
    ]
    if categorical:
        shown = ", ".join(terminal_safe(name) for name in categorical[:4])
        shown += ", ..." if len(categorical) > 4 else ""
        lines.append(f"  {plural(len(categorical), 'categorical column')}: {shown}")
    if refusable:
        lines += [
            "",
            f"  {plural(len(refusable), 'problem')} were NOT accepted, because a "
            "baseline",
            "  should be a file you trust and these describe damage:",
        ]
        for finding in refusable[:5]:
            lines.append(
                f"    {terminal_safe(finding.code):<28} "
                f"{terminal_safe(finding.column or 'file')}"
            )
        lines.append("")
        lines.append("  Fix them and run init again, or the definition of 'normal'")
        lines.append("  for this project will include them.")
    return "\n".join(lines)
